#!/usr/bin/env python3

"""
Prime Generator & Explorer Algorithm
This script explores prime numbers generated by subtracting 1 from the product
of powers of an initial set of sequential prime numbers.
It uses an optimized odometer-like algorithm with Aggressive Tree Pruning
for state-space exploration, power caching for performance, and a deterministic
64-bit Miller-Rabin primality test.
"""

from typing import Any, Mapping, Sequence, List
from numbers import Number
import sys
import os
import math
import time
from datetime import datetime

# Global state variables for the exploration space
log_path = None
exponents_list = None
exponents_list_ceiling = None
primes_list = None
power_cache = None
current_value = -1
max_num = -1


# -------------------------------------------------
# FAST PRIMALITY (Deterministic Miller–Rabin 64-bit)
# -------------------------------------------------

def is_prime(n: int) -> bool:
    """
    Determines if a number is prime using a deterministic Miller-Rabin test
    valid for all 64-bit integers.
    """
    if n < 2:
        return False

    if n in (2, 3, 5, 7, 11, 13, 17, 19, 23, 29):
        return True

    if n % 2 == 0 or n % 3 == 0 or n % 5 == 0:
        return False

    for p in (7, 11, 13, 17, 19, 23, 29):
        if n % p == 0:
            return False

    d = n - 1
    s = 0
    # Ottimizzazione: operatori bitwise invece della divisione
    while (d & 1) == 0:
        d >>= 1
        s += 1

    # Ottimizzazione Adattiva sui 64-bit (100% deterministica in entrambi i rami)
    if n < 1000000000000:
        bases = (2, 13, 23, 1662803)
    else:
        bases = (2, 325, 9375, 28178, 450775, 9780504, 1795265022)

    for a in bases:
        if a % n == 0:
            return True
        x = pow(a, d, n)
        if x == 1 or x == n - 1:
            continue
        for _ in range(s - 1):
            x = pow(x, 2, n)
            if x == n - 1:
                break
        else:
            return False
    return True


# -------------------------------------------------
# PRIME GENERATION (Sieve of Eratosthenes)
# -------------------------------------------------

def create_prime_list(n: int) -> List[int]:
    """
    Generates the first 'n' prime numbers using an optimized Sieve of Eratosthenes.
    """
    if n < 1:
        raise ValueError("n must be >= 1")

    if n < 6:
        limit = 15
    else:
        limit = int(n * (math.log(n) + math.log(math.log(n)))) + 5

    sieve = [True] * limit
    sieve[0:2] = [False, False]

    for i in range(2, int(limit ** 0.5) + 1):
        if sieve[i]:
            for j in range(i * i, limit, i):
                sieve[j] = False

    primes = [i for i, v in enumerate(sieve) if v]
    return primes[:n]


# -------------------------------------------------
# LOGGING UTILITIES
# -------------------------------------------------

def get_datetime():
    return "# " + datetime.now().strftime("%d/%m/%Y %H:%M:%S")


def init_log_file(id_value: int) -> None:
    global log_path
    log_dir = "log"
    os.makedirs(log_dir, exist_ok=True)
    timestamp = datetime.now().strftime("%d_%m_%y__%H_%M_%S")
    filename = f"{id_value}___{timestamp}.log"
    log_path = os.path.join(log_dir, filename)
    open(log_path, "a").close()


def log_print(value: Any) -> None:
    global log_path

    is_list_like = isinstance(value, Sequence) and not isinstance(value, (str, bytes, bytearray))

    if is_list_like:
        # SCRITTURA A BLOCCHI (CHUNKING) PER EVITARE MEMORY ERROR E TRONCAMENTI
        sys.stdout.write("# [")
        with open(log_path, "a", encoding="utf-8") as f:
            f.write("# [")
            
            chunk_size = 20000
            total_len = len(value)
            for i in range(0, total_len, chunk_size):
                chunk = value[i:i+chunk_size]
                chunk_str = ", ".join(map(str, chunk))
                if i > 0:
                    sys.stdout.write(", ")
                    f.write(", ")
                sys.stdout.write(chunk_str)
                f.write(chunk_str)
                
            sys.stdout.write("]\n")
            f.write("]\n")
        sys.stdout.flush()
        return

    # Gestione per tutti gli altri tipi
    if isinstance(value, str):
        printed = value
    elif isinstance(value, Mapping):
        printed = "{" + ", ".join(f"{k}: {v}" for k, v in value.items()) + "}"
    else:
        printed = str(value)

    is_number = isinstance(value, Number)
    starts_with_digit = printed.lstrip()[:1].isdigit()

    if starts_with_digit or is_number:
        out_line = printed
    else:
        if printed.startswith("#"):
            out_line = printed
        else:
            out_line = f"# {printed}"

    print(out_line, flush=True)

    with open(log_path, "a", encoding="utf-8") as f:
        f.write(out_line + "\n")


# -------------------------------------------------
# MATHEMATICAL BOUNDS & CACHING
# -------------------------------------------------

def max_num_computation(x):
    return x * x + 1


def init_exponents(lst):
    if len(lst) == 0:
        raise ValueError("The input list cannot be empty.")
    return [1] + [0] * (len(lst) - 1)


def logs_ceiling_by_bases(divisor):
    """
    Pre-computes the maximum allowed exponent for each prime base.
    Also pre-allocates a 2D power cache to replace expensive pow() calls.
    """
    global max_num, primes_list, exponents_list_ceiling, power_cache
    local_max_num = max_num // divisor
    if local_max_num <= 0:
        raise ValueError("max_num must be > 0")

    exponents_list_ceiling = [
        math.ceil(math.log(local_max_num, b))
        for b in primes_list
    ]

    power_cache = [
        [pow(b, e) for e in range(ceil + 2)]
        for b, ceil in zip(primes_list, exponents_list_ceiling)
    ]


# -------------------------------------------------
# CORE EXPLORATION ALGORITHM WITH DEEP PRUNING
# -------------------------------------------------

def next_exponents_under_max():
    """
    Generates the next valid combination of exponents using an 'odometer' approach
    augmented with Aggressive Tree Pruning to skip dead branches in the search space.
    """
    global exponents_list, primes_list, current_value, max_num, exponents_list_ceiling, power_cache

    min_num = primes_list[-1] + 1

    while True:
        index_to_check = 0
        exponents_list[index_to_check] += 1

        if exponents_list[-1] >= 2:
            return False

        # Normal Odometer carry-over for ceilings
        if exponents_list_ceiling[index_to_check] <= exponents_list[index_to_check]:
            while exponents_list_ceiling[index_to_check] <= exponents_list[index_to_check]:
                exponents_list[index_to_check] = 0
                index_to_check += 1
                exponents_list[index_to_check] += 1
                if exponents_list[-1] >= 2:
                    return False
        else:
            # Efficient candidate reconstruction via cache
            candidate_value = 1
            for i in range(len(exponents_list)):
                e = exponents_list[i]
                if e:
                    candidate_value *= power_cache[i][e]

            if candidate_value % 10 != 6:
                if candidate_value < max_num:
                    if min_num < candidate_value:
                        current_value = candidate_value - 1
                        return True
                else:
                    # CARRY OVER WITH AGGRESSIVE PRUNING
                    exponents_list[0] = 0
                    index_to_check = 1

                    while True:
                        if exponents_list_ceiling[index_to_check] > exponents_list[index_to_check]:
                            exponents_list[index_to_check] += 1

                            # --- PREDICTIVE SEARCH TREE PRUNING ---
                            min_cand = power_cache[0][1]
                            for i in range(1, len(exponents_list)):
                                e = exponents_list[i]
                                if e:
                                    min_cand *= power_cache[i][e]
                                    if min_cand >= max_num:
                                        break

                            if min_cand >= max_num:
                                exponents_list[index_to_check] = 0
                                if index_to_check == len(exponents_list) - 1:
                                    return False
                                index_to_check += 1
                                continue
                            # --------------------------------------
                            break
                        else:
                            exponents_list[index_to_check] = 0
                            if index_to_check == len(exponents_list) - 1:
                                return False
                            index_to_check += 1

                        if exponents_list[-1] >= 2:
                            return False


# -------------------------------------------------
# MAIN EXECUTION FLOW
# -------------------------------------------------

def main():
    global exponents_list, primes_list, current_value, max_num

    not_prime_counter = 0
    prime_counter = 0
    duplicate_counter = 0
    tot_primes = 0

    prime_list_found = []
    prime_list_found_set = set() # Ottimizzazione per rimozione bisect
    primes_to_explore = []
    primes_to_explore_set = set()

    data = "5"
    log_mode = "lf"

    if len(sys.argv) > 1:
        data = sys.argv[1].strip()
    if len(sys.argv) > 2:
        log_mode = sys.argv[2].strip().lower()

    verbose_logging = (log_mode == "lt")

    try:
        n = int(data)
    except ValueError:
        print("Error: invalid input", file=sys.stderr)
        sys.exit(1)

    init_log_file(n)

    start_dt = datetime.now()
    start_perf = time.perf_counter()
    print(f"# DATETIME_START: {start_dt.strftime('%d %m %Y %H %M %S')}")

    log_print("input value")
    log_print(n)

    primes_list = create_prime_list(n)
    input_prime = primes_list[-1]

    log_print("input prime")
    log_print(input_prime)

    max_num = max_num_computation(input_prime)
    current_value = input_prime

    log_print("max value")
    log_print(max_num)

    exponents_list = init_exponents(primes_list)
    logs_ceiling_by_bases(1)

    continue_computation = True

    while continue_computation:
        continue_computation = next_exponents_under_max()

        if continue_computation:
            if is_prime(current_value):
                # OTTIMIZZAZIONE O(1): Usiamo il set per i duplicati invece di list.insert() O(N)
                if current_value in prime_list_found_set:
                    duplicate_counter += 1
                else:
                    prime_counter += 1
                    prime_list_found_set.add(current_value)
                    prime_list_found.append(current_value)

                if current_value < (max_num // 2) and current_value not in primes_to_explore_set:
                    primes_to_explore.append(current_value)
                    primes_to_explore_set.add(current_value)
            else:
                not_prime_counter += 1

    # Ordiniamo alla fine (molto più efficiente che mantenere l'ordine ad ogni inserimento)
    prime_list_found.sort()

    big_prime_not_computed = primes_list[-1]
    prime_list_check = []

    start_val = big_prime_not_computed + 1
    if start_val % 2 == 0:
        if start_val == 2 and max_num > 2:
            if is_prime(2):
                if verbose_logging:
                    prime_list_check.append(2)
                tot_primes += 1
        start_val += 1

    for value in range(start_val, max_num, 2):
        if is_prime(value):
            # Ottimizzazione: Riempiamo l'array solo se dobbiamo fare verbose_logging ("lt")
            if verbose_logging:
                prime_list_check.append(value)
            tot_primes += 1

    if verbose_logging:
        log_print("prime list found")
        log_print(prime_list_found)
        log_print("prime to explore found")
        log_print(primes_to_explore)
        log_print("prime list check")
        log_print(prime_list_check)

    log_print(
        f"not prime counter: {not_prime_counter} -- "
        f"prime counter: {prime_counter} -- "
        f"duplicate counter: {duplicate_counter} -- "
        f"tot primes: {tot_primes}"
    )

    log_print("prime_counter/tot_primes")
    ratio_prime_counter_over_tot_primes = prime_counter / tot_primes if tot_primes else 0.0
    log_print(ratio_prime_counter_over_tot_primes)

    log_print("prime_counter / (not_prime_counter + prime_counter)")
    ratio_prime_counter_over_not_prime_counter_plus_prime_counter = prime_counter / (not_prime_counter + prime_counter) if (not_prime_counter + prime_counter) else 0.0
    log_print(ratio_prime_counter_over_not_prime_counter_plus_prime_counter)

    end_perf = time.perf_counter()
    end_dt = datetime.now()

    elapsed_ms = (end_perf - start_perf) * 1000

    log_print(f"# DATETIME_END: {end_dt.strftime('%d %m %Y %H %M %S')}")
    log_print("# Execution time (ms):")
    log_print(f"{elapsed_ms:.2f}")
    log_print("# COMPUTATION FINISHED")


if __name__ == "__main__":
    main()
